apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: jnbofori/reverseproxy:v3
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2000Mi"
            cpu: "650m"
          limits:
            memory: "4024Mi"
            cpu: "800m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
