apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: jnbofori/reverseproxy:latest
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "250m"
          limits:
            memory: "2024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
